name: Mi primer CI

# Eventos de ejecución (pushes y pull requests sobre main)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # Usamos una VM con Ubuntu

    permissions: # Agregamos los permisos necesarios para que el workflow pueda publicar paquetes(Subir imagenes buildeadas directamente a GHCR)
      contents: read
      packages: write

    steps:
      - name: Descarga del repo mediante checkout
        uses: actions/checkout@v4 # Action para pullear el codigo del repo

      - name: Instalar node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependencias
        run: npm ci # Este es el postintall que ejecuta prisma generate (ver package.json)

      - name: Lint
        run: npx eslint "{src,apps,libs,test}/**/*.ts"

      - name: Testing unitario
        run: npm test

      - name: Build de la app
        run: npm run build

      # Login, buildeo y push a GHCR
      - name: Login en GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build de la imagen de docker
        if: github.event_name == 'push'
        run: |
          docker build \
            -t ghcr.io/lautaro24fer/mi-api:${{ github.sha }} \
            -t ghcr.io/lautaro24fer/mi-api:latest \
            --label org.opencontainers.image.revision=${{ github.sha }} \
            --label org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
            .

      - name: Push de imagen a GHCR
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/lautaro24fer/mi-api:${{ github.sha }}
          docker push ghcr.io/lautaro24fer/mi-api:latest
